### PR TITLE
Create app vs site

### PR DESCRIPTION
**Pull request by HBoone16**

### CODE REVIEW

**Comment by amadeobr** [comment]
well done. excellent feedback, the code has improved immeasurably since your contribution

**Comment by HBoone16** [comment]
@bcohen99 @mromariz @amadeobr @RahulBansal85 plz give me feedback 

thumbs up bro

**Comment by bcohen99** [comment]
@HBoone16 @amadeobr I agree 100%, one thing I think you forgot to mention is the speed of change that a website enables relative to an app, which is very important for a new venture.  But otherwise, this was an excellent contribution to the code!!!!  Two thumbs up.

**Comment by amadeobr** [comment]
@HBoone16 @bcohen99 you bring up a fair point:

it reminds of the the following:
Old men of Argos, lieges of our realm, 
Shame shall not bid me shrink lest ye should see 
The love I bear my lord. Such blushing fear 
Dies at the last from hearts of human kind. 
From mine own soul and from no alien lips, 
I know and will reveal the life I bore. 
Reluctant, through the lingering livelong years, 
The while my lord beleaguered Ilion's wall. 

First, that a wife sat sundered from her lord, 
In widowed solitude, was utter woe 
And woe, to hear how rumour's many tongues 
All boded evil-woe, when he who came 
And he who followed spake of ill on ill, 
Keening Lost, lost, all lost! thro' hall and bower. 
Had this my husband met so many wounds, 
As by a thousand channels rumour told, 
No network e'er was full of holes as he. 
Had he been slain, as oft as tidings came 
That he was dead, he well might boast him now 
A second Geryon of triple frame, 
With triple robe of earth above him laid- 
For that below, no matter-triply dead, 
Dead by one death for every form he bore. 
And thus distraught by news of wrath and woe, 
Oft for self-slaughter had I slung the noose, 
But others wrenched it from my neck away. 
Hence haps it that Orestes, thine and mine, 
The pledge and symbol of our wedded troth, 
Stands not beside us now, as he should stand. 
Nor marvel thou at this: he dwells with one 
Who guards him loyally; 'tis Phocis' king, 
Strophius, who warned me erst, Bethink thee, queen, 
What woes of doubtful issue well may fall 
Thy lord in daily jeopardy at Troy, 
While here a populace uncurbed may cry, 
"Down witk the council, down!" bethink thee too, 
'Tis the world's way to set a harder heel 
On fallen power. 

For thy child's absence then 
Such mine excuse, no wily afterthought. 
For me, long since the gushing fount of tears 
Is wept away; no drop is left to shed. 
Dim are the eyes that ever watched till dawn, 
Weeping, the bale-fires, piled for thy return, 
Night after night unkindled. If I slept, 
Each sound-the tiny humming of a gnat, 
Roused me again, again, from fitful dreams 
Wherein I felt thee smitten, saw thee slain, 
Thrice for each moment of mine hour of sleep. 

All this I bore, and now, released from woe, 
I hail my lord as watch-dog of a fold, 
As saving stay-rope of a storm-tossed ship, 
As column stout that holds the roof aloft, 
As only child unto a sire bereaved, 
As land beheld, past hope, by crews forlorn, 
As sunshine fair when tempest's wrath is past, 
As gushing spring to thirsty wayfarer. 
So sweet it is to 'scape the press of pain. 
With such salute I bid my husband hail 
Nor heaven be wroth therewith! for long and hard 
I bore that ire of old. 

Sweet lord, step forth, 
Step from thy car, I pray-nay, not on earth 
Plant the proud foot, O king, that trod down Troy! 
Women! why tarry ye, whose task it is 
To spread your monarch's path with tapestry? 
Swift, swift, with purple strew his passage fair, 
That justice lead him to a home, at last, 
He scarcely looked to see.

[The attendant women spread the tapestry.]

For what remains, 
Zeal unsubdued by sleep shall nerve my hand 
To work as right and as the gods command.

**Comment by amadeobr** [comment]
image

**Comment by amadeobr** [comment]
image

**Pull request merged**
